#! /bin/sh

sxhkd -m 1 &
autorandr --change --force &
picom &

DISPLAYS=$(xrandr -q | grep -w connected | sed 's/connected //gm;s/primary //gm' | awk -F'[ +]' '{ print $1 " " $2 " " $3 " " $4 }' | sort -b -k4,4 -k3,3 | cut -d " " -f 1-2)
DISPLAY_NAMES=($(echo "${DISPLAYS}" | cut -d " " -f 1 | tr "\n" " "))
DISPLAY_COUNT=${#DISPLAY_NAMES[*]}

# Configure X and assign desktops
DESKTOPS=(I II III IV V VI VII VIII IX X)

if [[ $DISPLAY_COUNT -eq 1 ]]; then
    bspc monitor ${DISPLAY_NAMES[0]} -d "${DESKTOPS[@]}"
else
    bspc monitor ${DISPLAY_NAMES[0]} -d "${DESKTOPS[@]:0:5}"
    bspc monitor ${DISPLAY_NAMES[1]} -d "${DESKTOPS[@]:5:5}"
fi

# Global BSPWM config
bspc config border_width        1
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# GUI tools
dunst &
clipit &
flameshot &
enpass &
