#!/bin/sh

paru -S --needed --noconfirm \
    arandr \
    autorandr \
    bspwm \
    clipit \
    dunst \
    feh \
    flameshot \
    gvfs \
    i3lock-color \
    lxsession \
    mesa \
    noto-fonts-emoji \
    picom \
    polybar \
    rofi \
    sxhkd \
    thunar \
    thunar-archive-plugin \
    thunar-volman \
    ttf-fantasque-sans-mono \
    ttf-iosevka-nerd \
    vulkan-radeon \
    xf86-video-amdgpu \
    xorg-server \
    xorg-xinit \
    xorg-xrandr \
    xorg-xsetroot

ln -sf $(git rev-parse --show-toplevel)/.config/autorandr $HOME/.config
ln -sf $(git rev-parse --show-toplevel)/.config/dunst $HOME/.config
ln -sf $(git rev-parse --show-toplevel)/.config/bspwm $HOME/.config
ln -sf $(git rev-parse --show-toplevel)/.config/polybar $HOME/.config
ln -sf $(git rev-parse --show-toplevel)/.config/sxhkd $HOME/.config
ln -sf $(git rev-parse --show-toplevel)/.screenlayout $HOME
ln -sf $(git rev-parse --show-toplevel)/.xinitrc $HOME/.xinitrc
ln -sf $(git rev-parse --show-toplevel)/.xprofile $HOME/.xprofile
