#!/bin/sh

paru -S --needed --noconfirm \
	dolphin \
	flameshot \
	noto-fonts-emoji \
	picom \
	plasma-meta \
	ttf-fantasque-sans-mono \
	ttf-iosevka-nerd \
	vulkan-radeon \
	xf86-video-amdgpu \
	xorg-server \
	xorg-xinit \
	xorg-xrandr \
	xorg-xsetroot

ln -sf $(git rev-parse --show-toplevel)/.screenlayout $HOME
ln -sf $(git rev-parse --show-toplevel)/.xinitrc $HOME/.xinitrc
ln -sf $(git rev-parse --show-toplevel)/.xprofile $HOME/.xprofile
