#!/bin/sh

ln -sf $(git rev-parse --show-toplevel)/.zshrc $HOME/.zshrc
ln -sf $(git rev-parse --show-toplevel)/.zshenv $HOME/.zshenv
ln -sf $(git rev-parse --show-toplevel)/.p10k.zsh $HOME/.p10k.zsh
ln -sf $(git rev-parse --show-toplevel)/.p10k-ascii-8color.zsh $HOME/.p10k-ascii-8color.zsh

sh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/zsh4humans/v5/install)"
