#!/bin/sh

paru -S --needed --noconfirm zsh zplug

ln -sf $(git rev-parse --show-toplevel)/.zshrc $HOME/.zshrc
ln -sf $(git rev-parse --show-toplevel)/.p10k.zsh $HOME/.p10k.zsh

zsh -c 'source ~/.zshrc && zplug install'

chsh -s /usr/bin/zsh
