#!/bin/sh

paru -S --needed --noconfirm tmux

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

ln -sf $(git rev-parse --show-toplevel)/.tmux.conf $HOME/.tmux.conf
ln -sf $(git rev-parse --show-toplevel)/.config/tmux $HOME/.config
