#!/bin/sh

paru -S --noconfirm --needed \
	enpass-bin \
	networkmanager \
	networkmanager-openvpn

# Install nm scripts
sudo cp -r $(git rev-parse --show-toplevel)/networkmanager-scripts/* /etc/NetworkManager/dispatcher.d
sudo chmod a+rx /etc/NetworkManager/dispatcher.d/*
